version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 082684335586.dkr.ecr.us-east-1.amazonaws.com
     
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t nginx:latest .
      - docker tag nginx:latest 082684335586.dkr.ecr.us-east-1.amazonaws.com/nginx:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 082684335586.dkr.ecr.us-east-1.amazonaws.com/nginx:latest
artifacts:
  files:
    - '**/*'
