version: "3.3"

services:
  web:
    image: 395367784364.dkr.ecr.us-east-1.amazonaws.com/nginx:latest
    ports:
      - "80:80"
    networks:
      - mik
    restart: always
networks:
  mik:
    driver: bridge
